var hierarchy =
[
    [ "ch::syst::analysis", "structch_1_1syst_1_1analysis.html", null ],
    [ "ch::AutoRebin", "classch_1_1_auto_rebin.html", null ],
    [ "ch::syst::bin", "structch_1_1syst_1_1bin.html", null ],
    [ "ch::syst::bin_id", "classch_1_1syst_1_1bin__id.html", null ],
    [ "ch::BinByBinFactory", "classch_1_1_bin_by_bin_factory.html", null ],
    [ "BkgInfo", "struct_bkg_info.html", null ],
    [ "ch::CardWriter", "classch_1_1_card_writer.html", null ],
    [ "ch::syst::channel", "structch_1_1syst_1_1channel.html", null ],
    [ "ColInfo", "struct_col_info.html", null ],
    [ "ch::CombineHarvester", "classch_1_1_combine_harvester.html", null ],
    [ "convert_cpp_map_to_py_dict< TKey, TValue >", "structconvert__cpp__map__to__py__dict.html", null ],
    [ "convert_cpp_root_to_py_root< T >", "structconvert__cpp__root__to__py__root.html", null ],
    [ "convert_cpp_set_to_py_list< T >", "structconvert__cpp__set__to__py__list.html", null ],
    [ "convert_cpp_vector_to_py_list< T >", "structconvert__cpp__vector__to__py__list.html", null ],
    [ "convert_py_root_to_cpp_root< T >", "structconvert__py__root__to__cpp__root.html", null ],
    [ "convert_py_seq_to_cpp_vector< T >", "structconvert__py__seq__to__cpp__vector.html", null ],
    [ "convert_py_tup_to_cpp_pair< T, U >", "structconvert__py__tup__to__cpp__pair.html", null ],
    [ "ch::syst::era", "structch_1_1syst_1_1era.html", null ],
    [ "ch::FnTimer", "classch_1_1_fn_timer.html", null ],
    [ "ch::HistMapping", "structch_1_1_hist_mapping.html", null ],
    [ "ch::syst::mass", "structch_1_1syst_1_1mass.html", null ],
    [ "ch::Object", "classch_1_1_object.html", [
      [ "ch::Observation", "classch_1_1_observation.html", null ],
      [ "ch::Process", "classch_1_1_process.html", null ],
      [ "ch::Systematic", "classch_1_1_systematic.html", null ]
    ] ],
    [ "ch::Parameter", "classch_1_1_parameter.html", null ],
    [ "ch::syst::process", "structch_1_1syst_1_1process.html", null ],
    [ "ch::SOverBInfo", "structch_1_1_s_over_b_info.html", null ],
    [ "ch::syst::SystMap< T >", "classch_1_1syst_1_1_syst_map.html", null ],
    [ "ch::syst::SystMapAsymm< T >", "classch_1_1syst_1_1_syst_map_asymm.html", null ],
    [ "ch::FnTimer::Token", "classch_1_1_fn_timer_1_1_token.html", null ],
    [ "ch::tupleprint::TuplePrinter< Tuple, N >", "structch_1_1tupleprint_1_1_tuple_printer.html", null ],
    [ "ch::tupleprint::TuplePrinter< Tuple, 0 >", "structch_1_1tupleprint_1_1_tuple_printer_3_01_tuple_00_010_01_4.html", null ],
    [ "ch::tupleprint::TuplePrinter< Tuple, 1 >", "structch_1_1tupleprint_1_1_tuple_printer_3_01_tuple_00_011_01_4.html", null ]
];