#!/bin/bash

# obs_exp
INPUT="Mar26/results"; OUTPUT="Mar26/plots"; for M in A1_mu A1_5PD A1_5P A1_5D B1 B1ZZ K3 mEpsHiggs stage0 stage0ZZ K2_2D K3_5D; do mkdir -p ${OUTPUT}/${M}; for W in observed; do case ${W} in prefit_asimov) EXTRA='--main-label "SM Expected" --main-color 4';; postfit_asimov) EXTRA='--main-label "SM Expected" --main-color 2';; *) EXTRA="";; esac; for P in $(./getPOIs_hmm.py ${M} -P); do eval python scripts/plot1DScan.py -o scan_obs_exp_${W}_${M}_${P} --POI ${P} --model ${M}  --translate pois.json --meta "Types:${W},Scans:obs_exp,POIs:${P}" -m ${INPUT}/scan.${M}.${W}.nominal.${P}.root --other \"${INPUT}/scan.${M}.postfit_asimov.nominal.${P}.root:SM Expected:2\" --remove-near-min 0.8 --y-max 10 --chop 9 ${EXTRA} --no-input-label --outdir ${OUTPUT}/${M}; done; done; done

INPUT="Mar26/results"; OUTPUT="Mar26/plots"; for M in K1_mm_N1 L1_N1 K2_N1 K2Inv_N1 K2Undet_N1 L2_ldu_N1 L2flipped_ldu_N1 L2_llq_N1 K2{,Inv,Undet}Width_N1; do mkdir -p ${OUTPUT}/${M}; for W in observed; do case ${W} in prefit_asimov) EXTRA='--main-label "SM Expected" --main-color 4';; postfit_asimov) EXTRA='--main-label "SM Expected" --main-color 2';; *) EXTRA="";; esac; for P in $(./getPOIs_hmm.py ${M} -P); do eval python scripts/plot1DScan.py -o scan_obs_exp_${W}_${M}_${P} --POI ${P} --model ${M}  --translate pois.json --meta "Types:${W},Scans:obs_exp,POIs:${P}" -m ${INPUT}/scan.neg.${M}.${W}.nominal.${P}.root --other \"${INPUT}/scan.neg.${M}.postfit_asimov.nominal.${P}.root:SM Expected:2\" --remove-near-min 0.8 --y-max 10 --chop 9 ${EXTRA} --no-input-label --outdir ${OUTPUT}/${M}; done; done; done

# pub obs_exp
# INPUT="Mar26/results"; OUTPUT="Mar26/plots"; for M in A1_mu A1_5PD A1_5P A1_5D B1 B1ZZ K3 mEpsHiggs stage0 stage0ZZ K2_2D K3_5D; do mkdir -p ${OUTPUT}/${M}; for W in prefit_asimov postfit_asimov; do case ${W} in prefit_asimov) EXTRA='--main-label "SM Expected" --main-color 4';; postfit_asimov) EXTRA='--main-label "SM Expected" --main-color 2';; *) EXTRA="";; esac; for P in $(./getPOIs_hmm.py ${M} -P); do eval python scripts/plot1DScan.py -o scan_pub_${W}_${M}_${P} --POI ${P} --model ${M}  --translate pois.json --meta "Types:${W},Scans:pub,POIs:${P}" -m ${INPUT}/scan.${M}.${W}.nominal.${P}.root --other \"${INPUT}/scan.${M}.postfit_asimov.nominal.${P}.root:SM Expected:2\" --remove-near-min 0.8 --y-max 10 --chop 9 ${EXTRA} --no-input-label --outdir ${OUTPUT}/${M} --pub --no-numbers --legend-pos 2 --box-frac 0.7 --POI-line \"$(./getPOIs_hmm.py ${M} -P)\"; done; done; done

# INPUT="Mar26/results"; OUTPUT="Mar26/plots"; for M in K1_mm_N1 L1_N1 K2_N1 K2Inv_N1 K2Undet_N1 L2_ldu_N1 L2flipped_ldu_N1 L2_llq_N1; do mkdir -p ${OUTPUT}/${M}; for W in prefit_asimov postfit_asimov; do case ${W} in prefit_asimov) EXTRA='--main-label "SM Expected" --main-color 4';; postfit_asimov) EXTRA='--main-label "SM Expected" --main-color 2';; *) EXTRA="";; esac; for P in $(./getPOIs_hmm.py ${M} -P); do eval python scripts/plot1DScan.py -o scan_pub_${W}_${M}_${P} --POI ${P} --model ${M}  --translate pois.json --meta "Types:${W},Scans:pub,POIs:${P}" -m ${INPUT}/scan.neg.${M}.${W}.nominal.${P}.root --other \"${INPUT}/scan.${M}.postfit_asimov.nominal.${P}.root:SM Expected:2\" --remove-near-min 0.8 --y-max 10 --chop 9 ${EXTRA} --no-input-label --outdir ${OUTPUT}/${M} --pub --no-numbers --legend-pos 2 --box-frac 0.7 --POI-line \"$(./getPOIs_hmm.py ${M} -P)\"; done; done; done