#!/bin/bash

# stat_syst
INPUT="Mar26/results"; OUTPUT="Mar26/plots"; for M in A1_mu A1_5PD A1_5P A1_5D B1 B1ZZ K3 mEpsHiggs stage0 stage0ZZ K2_2D K3_5D; do mkdir -p ${OUTPUT}/${M}; for W in observed prefit_asimov postfit_asimov; do COL=1; case ${W} in prefit_asimov) COL=4; EXTRA='--main-label "SM Expected" --main-color 4';; postfit_asimov) COL=2; EXTRA='--main-label "SM Expected" --main-color 2';; *) EXTRA="";; esac; for P in $(./getPOIs_hmm.py ${M} -P); do eval python scripts/plot1DScan.py -o scan_${W}_${M}_${P} --POI ${P} --model ${M} --json ${OUTPUT}/${W}.json --translate pois.json --meta "Types:${W},Scans:stat_syst,POIs:${P}" -m ${INPUT}/scan.${M}.${W}.nominal.${P}.root --others \"${INPUT}/scan.${M}.${W}.fr.all.${P}.root:Freeze Syst.:${COL}\"  --breakdown "Syst,Stat" --remove-near-min 0.8 --y-max 10 --chop 9 ${EXTRA} --no-input-label --outdir ${OUTPUT}/${M}; done; done; done

INPUT="Mar26/results"; OUTPUT="Mar26/plots"; for M in K1_mm_N1 L1_N1 K2_N1 K2Inv_N1 K2Undet_N1 L2_ldu_N1 L2flipped_ldu_N1 L2_llq_N1 K2{,Inv,Undet}Width_N1; do mkdir -p ${OUTPUT}/${M}; for W in observed prefit_asimov postfit_asimov; do COL=1; case ${W} in prefit_asimov) COL=4; EXTRA='--main-label "SM Expected" --main-color 4';; postfit_asimov) COL=2; EXTRA='--main-label "SM Expected" --main-color 2';; *) EXTRA="";; esac; for P in $(./getPOIs_hmm.py ${M} -P); do eval python scripts/plot1DScan.py -o scan_${W}_${M}_${P} --POI ${P} --model ${M} --json ${OUTPUT}/${W}.json --translate pois.json --meta "Types:${W},Scans:stat_syst,POIs:${P}" -m ${INPUT}/scan.neg.${M}.${W}.nominal.${P}.root --others \"${INPUT}/scan.${M}.${W}.fr.all.${P}.root:Freeze Syst.:${COL}\"  --breakdown "Syst,Stat" --remove-near-min 0.8 --y-max 10 --chop 9 ${EXTRA} --no-input-label --outdir ${OUTPUT}/${M}; done; done; done


# INPUT="Comb_Mar26/results"; OUTPUT="Comb_Mar26/plots"; for M in mEpsHiggs; do mkdir -p ${OUTPUT}/${M}; for W in observed postfit_asimov; do COL=1; case ${W} in prefit_asimov) COL=4; EXTRA='--main-label "SM Expected" --main-color 4';; postfit_asimov) COL=2; EXTRA='--main-label "SM Expected" --main-color 2';; *) EXTRA="";; esac; for P in $(./getPOIs_hmm.py ${M} -P); do eval python scripts/plot1DScan.py -o scan_${W}_${M}_${P} --POI ${P} --model ${M} --json ${OUTPUT}/${W}.json --translate pois.json --meta "Types:${W},Scans:stat_syst,POIs:${P}" -m ${INPUT}/scan.${M}.${W}.nominal.${P}.root --remove-near-min 0.8 --y-max 10 --chop 9 ${EXTRA} --no-input-label --outdir ${OUTPUT}/${M}; done; done; done

#INPUT="Mar26/results"; M=A1_mu; W=observed; P=mu; python scripts/plot1DScanNew.py -i nominal:${INPUT}/scan.${M}.${W}.nominal.${P}.root:MarkerColor=1:LineColor=1 fr_all:${INPUT}/scan.${M}.${W}.fr.all.${P}.root:MarkerSize=0.5,MarkerColor=1:LineColor=1,LineStyle=2 --var ${P} --values-box "0.65,0.75,0.95,0.93" --y-max 10 --chop 9
